### ISSUE TITLE
Suspect logic in GetFunctionByName

### ISSUE THREAD

**Issue by meck-gd** [kevoreilly/capemon#110]
Hi,

I'm currently debugging a problem that seems to stem from some broken logic introduced by 1ca0a99465e0550c4114e24392abbab481cae647.

```c
	for (SIZE_T i = 0; i < FuncCount; i++)
		for (SIZE_T j = 0; j < FoundCount; j++)
			if (results[j].FunctionName && results[j].Address && !strcmp(results[j].FunctionName, YaraFunctions[i]))
				return results[j].Address;
```

`GetFunctionByName` is supposed to return a specific function pointer based on the `FunctionName` parameter given to it. However, in these final nested loops, the parameter is not involved in any way. It compares the results against the hard-coded `YaraFunctions` array and then more or less randomly returns an address that has nothing to do with what was asked for by the caller.

From what I can tell, the outer loop should be removed and the `strcmp` should happen against `FunctionName` as second parameter, or am I missing something?

Taking back a step, perhaps the scan can should also be skipped entirely if `FunctionName` is not a member of `YaraFunctions`.

**Comment by kevoreilly** [comment]
Yes I think you're absolutely right! Not sure I can defend the logic there...

Proposed fix:

```
diff --git a/CAPE/CAPE.c b/CAPE/CAPE.c
index 7824b40..9bf136e 100644
--- a/CAPE/CAPE.c
+++ b/CAPE/CAPE.c
@@ -707,6 +707,19 @@ PVOID GetFunctionByName(HMODULE ModuleBase, PCHAR FunctionName)
                "vDbgPrintExWithPrefixInternal",
        };

+       BOOL InYaraFunctions = FALSE;
+       for (SIZE_T i = 0; YaraFunctions[i]; i++)
+       {
+               if (!_stricmp(YaraFunctions[i], FunctionName))
+               {
+                       InYaraFunctions = TRUE;
+                       break;
+               }
+       }
+
+       if (!InYaraFunctions)
+               return NULL;
+
        SIZE_T FoundCount = 0, FuncCount = sizeof(YaraFunctions) / sizeof(YaraFunctions[0]);
        NameByAddress* results = GetAddressesByYara(ModuleBase, YaraFunctions, FuncCount, &FoundCount);

@@ -717,10 +730,9 @@ PVOID GetFunctionByName(HMODULE ModuleBase, PCHAR FunctionName)
                return NULL;
        }

-       for (SIZE_T i = 0; i < FuncCount; i++)
-               for (SIZE_T j = 0; j < FoundCount; j++)
-                       if (results[j].FunctionName && results[j].Address && !strcmp(results[j].FunctionName, YaraFunctions[i]))
-                               return results[j].Address;
+       for (SIZE_T j = 0; j < FoundCount; j++)
+               if (results[j].FunctionName && results[j].Address && !strcmp(results[j].FunctionName, FunctionName))
+                       return results[j].Address;

        return NULL;
 }
```

Thanks for reporting this, apologies for the poor code.

**Comment by meck-gd** [comment]
No worries 🙂 

The diff looks good to me! Only one thing, if you're using `stricmp` for `InYaraFunctions`, wouldn't it make sense to use it in the final loop as well?

**Comment by kevoreilly** [comment]
Yes indeed I've fixed that as well as the missing ``free()`` at the end 👍 Thanks for your help

**Comment by kevoreilly** [comment]
Fixed in https://github.com/kevoreilly/capemon/commit/1dbb0b1e7b7542f4c869918692230e38a0a73081 - thanks again

**Comment by meck-gd** [comment]
@kevoreilly 
Hey, I just took a look at the commit diff and noticed two things I missed earlier. Sorry 😅 

1. The loop condition of `YaraFunctions[i]` looks really unsafe, because the array is not NULL-terminated. `i < ARRAYSIZE(YaraFunctions)` would work better?
2. `free(results)` doesn't happen if the loop returns a function pointer.

**Comment by kevoreilly** [comment]
Arghhhh with every commit I feel more stupid.

https://github.com/kevoreilly/capemon/commit/04387f3a025ef932f06ae0061ce47824d82e9c7d

Thanks!
